
    'Constitución Política','Ley Federal del Trabajo',
    'Código de Comercio','Codigo Penal Federal',
    'Ley de Amparo','Ley General de Títulos y Operaciones de Crédito',
    'Código Civil · Aguascalientes','Código Civil · Baja California',
    'Código Civil · Baja California Sur','Código Civil · Campeche',
    'Código Civil · Chiapas','Código Civil · Chihuahua',
    'Código Civil · Ciudad de México','Código Civil · Coahuila',
    'Código Civil · Colima','Código Civil · Durango',
    'Código Civil · Estado de México','Código Civil · Guanajuato',
    'Código Civil · Guerrero','Código Civil · Hidalgo',
    'Código Civil · Jalisco',
    'Ley Federal del Trabajo',
    'Código Civil · Michoacán',
    'Código Civil · Morelos','Código Civil · Nayarit',
    'Código Civil · Nuevo León','Código Civil · Oaxaca',
    'Código Civil · Puebla','Código Civil · Querétaro',
    'Código Civil · Quintana Roo','Código Civil · San Luis Potosí',
    'Código Civil · Sinaloa','Código Civil · Sonora',
    'Código Civil · Tabasco','Código Civil · Tamaulipas',
    'Código Civil · Tlaxcala','Código Civil · Veracruz',
    'Código Civil · Yucatán','Código Civil · Zacatecas'
