
    'Autorský zákon','Daňový řád','Energetický zákon','Exekuční řád',
    'Insolvenční zákon','Listina základních práv a svobod','Notářský řád',
    'Občanský soudní řád','Školský zákon','Správní řád','Stavební zákon',
    'Trestní řád','Trestní zákoník','Ústava České republiky',
    'Zákon o advokacii','Zákon o archivnictví','Zákon o auditorech',
    'Zákon o azylu','Zákon o bankách','Zákon o cenách',
    'Zákon o cestovních dokladech','Zákon o církvích',
    'Zákon o civilním letectví',
    'Občanský zákoník',
    'Zákon o dani z nemovitých věcí',
    'Zákon o dani z přidané hodnoty','Zákon o daních z příjmů',
    'Zákon o dětské skupině','Zákon o dráhách',
    'Zákon o důchodovém pojištění','Zákon o elektronických komunikacích',
    'Zákon o hazardních hrách','Zákon o hlavním městě Praze',
    'Zákon o katastru nemovitostí','Zákon o krajích',
    'Zákon o kybernetické bezpečnosti','Zákon o léčivech',
    'Zákon o lesích','Zákon o matrikách','Zákon o mediaci',
    'Zákon o mezinárodním právu soukromém',
    'Zákon o nemocenském pojištění',
    'Zákon o obchodních korporacích','Zákon o obcích',
    'Zákon o ochraně hospodářské soutěže','Zákon o ochraně ovzduší',
    'Zákon o ochraně přírody a krajiny','Zákon o ochraně spotřebitele',
    'Zákon o ochranných známkách','Zákon o odpadech',
    'Zákon o platebním styku','Zákon o pobytu cizinců',
    'Zákon o podnikání na kapitálovém trhu','Zákon o pojišťovnictví',
    'Zákon o Policii ČR','Zákon o pozemních komunikacích',
    'Zákon o přestupcích','Zákon o rozhodčím řízení',
    'Zákon o silničním provozu','Zákon o sociálních službách',
    'Zákon o soudech a soudcích','Zákon o spotřebitelském úvěru',
    'Zákon o státní službě','Zákon o účetnictví',
    'Zákon o Ústavním soudu','Zákon o územním plánování',
    'Zákon o veřejném ochránci práv','Zákon o veřejném zdravotním pojištění',
    'Zákon o veřejných dražbách','Zákon o veřejných rejstřících',
    'Zákon o vlastnictví bytů','Zákon o vodách',
    'Zákon o volbách do Parlamentu ČR','Zákon o vynálezech',
    'Zákon o vysokých školách','Zákon o zadávání veřejných zakázek',
    'Zákon o zaměstnanosti','Zákon o zbraních',
    'Zákon o zdravotních službách','Zákon o znalcích',
    'Zákon o zpracování osobních údajů',
    'Zákoník práce','Živnostenský zákon'