# -*- coding: utf-8 -*-
import json

with open('countries/cz.json','r',encoding='utf-8') as f: cz = json.load(f)
with open('countries/mx.json','r',encoding='utf-8') as f: mx = json.load(f)

cz_new = {
    "CHECK_1": "Prohledá 97 zákonů v reálném čase — za sekundy, ne hodiny",
    "CHECK_2": "Cituje přesný § s plným zněním u každé odpovědi",
    "CHECK_3": "Porovná až 3 právní řády současně v jednom dotazu",
    "CHECK_4": "Najde nejrelevantnější soudní rozhodnutí k vašemu případu",
    "CHECK_5": "Zeptejte se na svůj případ — AI konzultuje celou legislativu",
    "CHECK_6": "Ptejte se v češtině, odpovědi i z německého či španělského práva",
    "CHECK_7": "Přístup k 1 465 rozhodnutím Ústavního a Nejvyššího soudu",
    "CHECK_8": "Nulové halucinace — každá odpověď je ověřitelná u zdroje",
    "CHECK_9": "Procházejte zákon hierarchicky — část, hlava, díl, paragraf",
    "CHECK_10": "Generování procesních diagramů z právní struktury",
    "PROOF_SUB": "Případ vyžadující české pracovní právo, španělské pracovní právo, mezinárodní právo soukromé EU — a precedenty Ústavního soudu. Magnus zvládá vše najednou.",
    "PROOF_CASE": "\u201eŠpanělský architekt, 5 let v Praze, propuštěn bez výpovědi českým zaměstnavatelem. Tři týdny nevyplacené mzdy. Plánuje se vrátit do Španělska \u2014 chce žalovat před odjezdem.\u201c",
    "PROOF_COUNTRIES": "Česká republika · Španělsko",
    "PROOF_VERDICT": "KRITICKÉ ZJIŠTĚNÍ: Český § 72 stanoví 2měsíční lhůtu pro napadení platnosti výpovědi. Španělské právo umožňuje 1 rok. Záměna lhůty = prohra. Magnus to zjistil za 45 sekund.",
    "PROOF_RESULTS_LABEL": "Co Magnus nalezl · 24 článků · 2 jurisdikce",
    "PROOF_ART1": "§ 72 · Zákoník práce", "PROOF_TXT1": "2měsíční lhůta pro napadení platnosti výpovědi. Již běží.",
    "PROOF_ART2": "§ 141 · Zákoník práce", "PROOF_TXT2": "Mzda splatná bez ohledu na způsob ukončení pracovního poměru.",
    "PROOF_ART3": "čl. 56 · Estatuto de los Trabajadores", "PROOF_TXT3": "Neoprávněné propuštění: 33 dnů za každý rok trvání poměru.",
    "PROOF_ART4": "Řím I čl. 8 · Brusel I bis čl. 21", "PROOF_TXT4": "Rozhodné právo: české. Příslušný soud: český. Vykonatelné ve Španělsku.",
    "PROOF_FLAG1": "🇨🇿", "PROOF_FLAG2": "🇨🇿", "PROOF_FLAG3": "🇪🇸", "PROOF_FLAG4": "🇪🇺",
    "MAGNUS_FEAT_DESC": "Jediný AI systém, který prohledá <strong>více právních systémů současně</strong>. Popište případ v libovolném jazyce, vyberte až 3 jurisdikce — Magnus dohledá ověřené články a sestaví srovnávací analýzu. Včetně kolize právních řádů.",
    "MAGNUS_PILL1": "🇨🇿 Česko", "MAGNUS_PILL2": "🇪🇸 España",
    "JURIS_FEAT_DESC": "Popište svůj případ. AI najde nejrelevantnější nálezy Ústavního soudu a rozhodnutí Nejvyššího soudu — podle obsahu, ne klíčových slov.",
    "KNIHOVNA_FEAT_DESC": "97 zákonů v plném znění. Procházejte hierarchicky — část, hlava, díl, paragraf. Na každém článku <strong>chat s AI</strong>, který rozumí kontextu celého zákona. Generování procesních diagramů jedním kliknutím.",
    "ATLAS_FEAT_DESC": "Každý § který váš případ podporuje — a každý, který mu odporuje. Atlas sestaví <strong>dialektickou mapu</strong> celého případu a vizualizuje ji jako 3D sluneční soustavu právní gravitace. Vidíte slabiny dříve než oponent.",
    "JURIS_R1_CASO": "21 Cdo 2152/2004", "JURIS_R1_TRIBUNAL": "Nejvyšší soud",
    "JURIS_R1_RATIO": "Posudek o pracovní činnosti může obsahovat kromě hodnocení práce zaměstnance rovněž jakékoliv další skutečnosti, jestliže mají vztah k výkonu práce.",
    "JURIS_R2_CASO": "31 Cdo 2955/2023", "JURIS_R2_TRIBUNAL": "Nejvyšší soud",
    "JURIS_R2_RATIO": "Zaměstnavatel může odstoupit od konkurenční doložky po dobu trvání pracovního poměru zaměstnance i na základě smluvního ujednání.",
    "JURIS_R3_CASO": "III.ÚS 84/25", "JURIS_R3_TRIBUNAL": "Ústavní soud · Sala IV",
    "JURIS_R3_RATIO": "Nerespektování závěrů kasačního nálezu Ústavního soudu ve věci exekuce na majetek zaměstnance.",
    "MM_R1_ART": "§ 708 · Občanský zákoník", "MM_R1_TXT": "To, co manželům náleží, má majetkovou hodnotu a není vyloučeno z právních poměrů, je součástí společného jmění manželů.",
    "MM_R2_ART": "§ 49 · Zákon o mezinárodním právu soukromém", "MM_R2_TXT": "Osobní poměry manželů se řídí právním řádem státu, jehož jsou oba občany.",
    "MM_R3_ART": "Art. 9 · Código Civil", "MM_R3_TXT": "La ley personal correspondiente a las personas físicas es la determinada por su nacionalidad.",
    "MM_R4_ART": "Art. 1316 · Código Civil", "MM_R4_TXT": "A falta de capitulaciones o cuando éstas sean ineficaces, el régimen será el de la sociedad de gananciales.",
    "CHIP1_QUERY": "Propuštění ze zaměstnání", "CHIP1_LABEL": "Pracovní právo",
    "CHIP2_QUERY": "Náhrada škody, odpovědnost", "CHIP2_LABEL": "Občanské právo",
    "CHIP3_QUERY": "Trestní oznámení, obhajoba", "CHIP3_LABEL": "Trestní právo",
    "CHIP4_QUERY": "Smlouva, obchodní spor", "CHIP4_LABEL": "Obchodní právo",
    "CHIP5_QUERY": "Insolvence, oddlužení", "CHIP5_LABEL": "Insolvence",
    "STRIP1": "Občanský zákoník</span> · 3 079 §", "STRIP2": "Zákoník práce</span> · 396 §",
    "STRIP3": "Zákon o obchodních korporacích</span> · 786 §", "STRIP4": "Trestní zákoník</span> · 421 §",
    "STRIP5": "Insolvenční zákon</span> · 434 §", "STRIP6": "<span>1 465</span> rozhodnutí soudů ČR",
    "STRIP7": "<span>97</span> zákonů · 19 772 paragrafů", "STRIP8": "<span>0</span> halucinací · skutečný text vždy citován",
}

mx_new = {
    "CHECK_1": "Busca en 7 leyes y 32 códigos civiles en tiempo real — en segundos",
    "CHECK_2": "Cita el artículo exacto con texto completo en cada respuesta",
    "CHECK_3": "Compara hasta 3 sistemas jurídicos simultáneamente en una consulta",
    "CHECK_4": "Encuentra las resoluciones judiciales más relevantes para tu caso",
    "CHECK_5": "Pregunta sobre tu caso — la AI consulta toda la legislación aplicable",
    "CHECK_6": "Pregunta en español, respuestas también del derecho checo, alemán o francés",
    "CHECK_7": "Acceso a 94 937 artículos verificados en la base de datos",
    "CHECK_8": "Cero alucinaciones — cada respuesta es verificable en la fuente",
    "CHECK_9": "Navega la ley jerárquicamente — libro, título, capítulo, artículo",
    "CHECK_10": "Generación de diagramas de proceso desde la estructura legal",
    "PROOF_SUB": "Un caso que requiere derecho laboral mexicano, código civil estatal y la Constitución — simultáneamente. Magnus lo resuelve todo de una vez.",
    "PROOF_CASE": "\"Ingeniero extranjero, 3 años en CDMX, despedido sin aviso. Tres semanas de salario sin pagar. Quiere demandar antes de regresar a su país.\"",
    "PROOF_COUNTRIES": "México · Ley Federal del Trabajo",
    "PROOF_VERDICT": "HALLAZGO CRÍTICO: El Art. 518 de la LFT establece un plazo de 2 meses para impugnar el despido. Dejar pasar el plazo = derrota. Magnus lo encontró en 45 segundos.",
    "PROOF_RESULTS_LABEL": "Lo que Magnus encontró · artículos relevantes",
    "PROOF_ART1": "Art. 47 · Ley Federal del Trabajo", "PROOF_TXT1": "Causales de rescisión sin responsabilidad para el patrón.",
    "PROOF_ART2": "Art. 48 · Ley Federal del Trabajo", "PROOF_TXT2": "Reinstalación o indemnización a elección del trabajador.",
    "PROOF_ART3": "Art. 518 · Ley Federal del Trabajo", "PROOF_TXT3": "Prescripción: 2 meses para acciones por despido.",
    "PROOF_ART4": "Art. 123 · Constitución Política", "PROOF_TXT4": "Derecho al trabajo digno. Tribunal: Junta de Conciliación y Arbitraje.",
    "PROOF_FLAG1": "🇲🇽", "PROOF_FLAG2": "🇲🇽", "PROOF_FLAG3": "🇲🇽", "PROOF_FLAG4": "🇲🇽",
    "MAGNUS_FEAT_DESC": "El único sistema de AI que busca en <strong>múltiples sistemas jurídicos simultáneamente</strong>. Describe tu caso en cualquier idioma, selecciona hasta 3 jurisdicciones — Magnus encuentra los artículos verificados y construye un análisis comparativo.",
    "MAGNUS_PILL1": "🇲🇽 México", "MAGNUS_PILL2": "🇨🇿 Česko",
    "JURIS_FEAT_DESC": "Describe tu caso. La AI encuentra los artículos más relevantes de la Constitución, códigos civiles y leyes federales — por contenido, no palabras clave.",
    "KNIHOVNA_FEAT_DESC": "7 leyes en texto completo. Navega jerárquicamente — libro, título, capítulo, artículo. En cada artículo <strong>chat con AI</strong> que entiende el contexto de toda la ley. Generación de diagramas con un clic.",
    "ATLAS_FEAT_DESC": "Cada artículo que apoya tu caso — y cada uno que lo contradice. Atlas construye un <strong>mapa dialéctico</strong> del caso completo y lo visualiza como sistema solar 3D. Ves las debilidades antes que tu oponente.",
    "JURIS_R1_CASO": "Art. 47 · LFT", "JURIS_R1_TRIBUNAL": "Ley Federal del Trabajo",
    "JURIS_R1_RATIO": "Son causas de rescisión de la relación de trabajo, sin responsabilidad para el patrón.",
    "JURIS_R2_CASO": "Art. 48 · LFT", "JURIS_R2_TRIBUNAL": "Ley Federal del Trabajo",
    "JURIS_R2_RATIO": "El trabajador podrá solicitar que se le reinstale en el trabajo o que se le indemnice.",
    "JURIS_R3_CASO": "Art. 123 · CPEUM", "JURIS_R3_TRIBUNAL": "Constitución Política",
    "JURIS_R3_RATIO": "Toda persona tiene derecho al trabajo digno y socialmente útil.",
    "MM_R1_ART": "Art. 48 · Ley Federal del Trabajo", "MM_R1_TXT": "El trabajador podrá solicitar ante la Autoridad Conciliadora que se le reinstale o indemnice.",
    "MM_R2_ART": "Art. 50 · Ley Federal del Trabajo", "MM_R2_TXT": "Las indemnizaciones consistirán en una cantidad igual al importe de los salarios.",
    "MM_R3_ART": "Art. 123 · Constitución Política", "MM_R3_TXT": "Toda persona tiene derecho al trabajo digno y socialmente útil.",
    "MM_R4_ART": "Art. 518 · Ley Federal del Trabajo", "MM_R4_TXT": "Prescriben en dos meses las acciones de los trabajadores que sean separados del trabajo.",
    "CHIP1_QUERY": "Despido injustificado", "CHIP1_LABEL": "Derecho laboral",
    "CHIP2_QUERY": "Arrendamiento, contratos", "CHIP2_LABEL": "Derecho civil",
    "CHIP3_QUERY": "Denuncia penal, defensa", "CHIP3_LABEL": "Derecho penal",
    "CHIP4_QUERY": "Constitución de sociedad", "CHIP4_LABEL": "Derecho mercantil",
    "CHIP5_QUERY": "Juicio de amparo", "CHIP5_LABEL": "Amparo",
    "STRIP1": "Constitución</span> · 333 arts", "STRIP2": "Ley Federal del Trabajo</span> · 1 150 arts",
    "STRIP3": "Código de Comercio</span> · 1 530 arts", "STRIP4": "Código Penal Federal</span> · 480 arts",
    "STRIP5": "Ley de Amparo</span> · 271 arts", "STRIP6": "<span>94 937</span> artículos totales",
    "STRIP7": "<span>7</span> leyes · 32 estados", "STRIP8": "<span>0</span> alucinaciones · texto real siempre citado",
}

cz.update(cz_new)
mx.update(mx_new)

with open('countries/cz.json','w',encoding='utf-8') as f: json.dump(cz, f, ensure_ascii=False, indent=2)
with open('countries/mx.json','w',encoding='utf-8') as f: json.dump(mx, f, ensure_ascii=False, indent=2)
print(f'CZ: {len(cz)} keys | MX: {len(mx)} keys')
